name: PubMed Test

on:
  workflow_dispatch:

jobs:
  run-pubmed:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PubMed Script
        run: |
          python ingest_pubmed.py
          
      - name: Run RSS Script
        run: |          
          python ingest_rss.py
          
      - name: Run Classifier
        run: |
          python classify_records.py

      - name: Generate report
        run: python generate_report.py

      - name: Upload Intelligence Package
        uses: actions/upload-artifact@v4
        with:
          name: pharma-intelligence-output
          path: |
            data/*.json
            data/report.md
