name: PubMed Test

on:
  workflow_dispatch:

jobs:
  run-pubmed:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PubMed Script
        run: |
          python ingest_pubmed.py
          
      - name: Run RSS Script
        run: |          
          python ingest_rss.py

      - name: Upload PubMed Results
        uses: actions/upload-artifact@v4
        with:
          name: pubmed-results
          path: data/pubmed_results.json

      - name: Upload RSS Results
        uses: actions/upload-artifact@v4
        with:
          name: rss-results
          path: data/rss_results.json
